use employee;

select * from customer;
select * from passenger;
select * from ticket_details;
select * from routes;
-- display customer first_name.lastname,and travel date for all passengers;

select * from customer; 
select first_name, last_name from customer; 
select * from customer where customer_id=2;

select c.first_name,c.last_name,
p.travel_date from customer c
inner join passenger p
on c.customer_id = p.customer_id;

select * from customer;
select * from ticket_details;

select c.first_name, c.last_name,
t.brand from customer c
inner join ticket_details t 
on c.customer_id = t.customer_id;




-- 2. select customename,flight number,departure airport and arrival airport

select c.first_name,c.last_name,
r.flight_num,r.origin_airport,r.destination_airport
from customer c
join passenger ppassenger
on c.customer_id = p.customer_id
join routes r 
on p.route_id = r.route_id;

-- display customername,routedetails and seat number
select c.first_name,c.last_name,
r.*,p.seat_num
from customer c 
join passenger p
on c.customer_id = p.customer_id
join routes r
on p.route_id = r.route_id;

-- display customer name,number of tickets booked and total amount paid

select c.first_name,c.last_name, t.no_of_tickets,t.price_per_ticket,
(t.no_of_tickets * t.price_per_ticket) as total_price_per_ticket
from customer c 
join ticket_details t
on c.customer_id = t.customer_id;

-- display route_wise total revenue genertaed from ticket bookings
select r.route_id,sum(t.price_per_ticket)
from routes r
join passenger p
on r.route_id = p.route_id
join ticket_details t
on p.customer_id = t.customer_id
group by r.route_id
order by r.route_id asc;


select * from customer;
select * from passenger;
select * from ticket_details;
select * from routes;

-- subqueries
-- find customers who purchased the maximun no of tickets
 select *
 from ticket_details where
 no_of_tickets = (select max(no_of_tickets) from ticket_details);
 
 -- find routes having a distance greater than the average distance
 
 select * from routes
 where distance_miles >
 (select avg(distance_miles) from routes);


-- find customers who paid the highest ticket amount

select c.*, (t.no_of_tickets * t.price_per_ticket) as max_ticket_price from customer c
join ticket_details t
on c.customer_id = t.customer_id
where (t.no_of_tickets * t.price_per_ticket) =
(select max(no_of_tickets * price_per_ticket) from ticket_details);

-- find flights generating revenue greater than average flight revenue

select r.flight_num,sum(t.no_of_tickets*t.price_per_ticket) as total_revenue from
routes r
join  passenger p
on r.route_id = p.route_id
join ticket_details t
on p.customer_id = t.customer_id
group by r.flight_num
having sum(t.no_of_tickets*t.price_per_ticket)>
(
   select avg(total_revenue)
   from
   (

     select sum(no_of_tickets*price_per_ticket) total_revenue 
     from ticket_details
     group by customer_id
   )x 
);

select * from customer;
select * from passenger;
select * from ticket_details;
select * from routes;

-- group by
-- count customer by gender
select gender,count(*) as gender_count
from customer
group by gender;

-- count passengers by class
select class_id,count(*) as passenger_count
from passenger
group by class_id;

-- find total tickets booked by each customer

select customer_id,sum(no_of_tickets) as total_tickets
from ticket_details
group by customer_id;

-- find total revenue generated by each airline brand

select brand,sum(no_of_tickets * price_per_ticket) as total_revenue
from ticket_details
group by brand;

-- find average ticket price by class

select class_id,avg(price_per_ticket)
from ticket_details
group by class_id;

-- views

-- create view to display customer details
-- (customer_id,first_name,last_name,gender)

select * from customer;
select * from passenger;
select * from ticket_details;
select * from routes;

create  view cus_view as 
select * from customer; 

select * from cus_view;

-- create view showing customer names along with their travel dates

create view customer_travel_dates
as
select c.first_name,c.last_name,
p.travel_date from customer c 
join passenger p
on c.customer_id = p.customer_id;

select * from customer_travel_dates;

-- create view displaying flight number,origin airport,destination airport and distance miles

create view route_details
as
select flight_num,origin_airport,destination_airport,distance_miles
from routes;

select * from route_details;

-- create a view shwoing customer name and total amount paid(no_of_tickets * price_per_ticket)

drop view vw_customer_payement;

create view vw_customer_payement 
as
select c.first_name,c.last_name,
(no_of_tickets * price_per_ticket) as total_amount
from customer c
join ticket_details t
on c.customer_id = t.customer_id;

select * from vw_customer_payement;


-- rollup

-- Display total tickets booked by each customer and a grand total
select * from customer;
select * from passenger;
select * from ticket_details;
select * from routes;  


select customer_id,
sum(no_of_tickets) as total_tickets
from ticket_details
group by customer_id with rollup; 


-- Display total revenue by airline brand and grand total.
select brand ,sum(no_of_tickets * price_per_ticket) as total_revenue
from ticket_details
group by brand with rollup;

-- display total passengers by class and grand total

select class_id,
count(*) passenger_count from passenger
group by class_id with rollup;
 
 
 -- cte
 -- create a cte to show total tickets booked by each customer
 
 with customer_tickets
 as
 (
 select customer_id,sum(no_of_tickets) as total_tickets
 from ticket_details
 group by customer_id
 )
 select * from customer_tickets;
 
 -- create a cte to show total revenue generated by each brand
 
 with revenue_brand as
 (
 select brand,sum(no_of_tickets * price_per_ticket) as total_revenue
 from ticket_details
 group by brand
 )
 select * from revenue_brand;
 
 -- find customers who booked more than 5 tickets using a cte
 
 
 with customer_tickets 
 as
 (
 select customer_id,sum(no_of_tickets) total_tickets
 from ticket_details
 group by customer_id
 )
 select * from customer_tickets
 where total_tickets > 2;
 
 -- find brand generating revenue greater than 50000 using cte
 
 select * from ticket_details;

with brand_revenue as
( 
 select brand ,sum(no_of_tickets * price_per_ticket) total_revenue
 from ticket_details
 group by brand
 )
 select * from brand_revenue
 where total_revenue > 3000;
 
 -- top revenue generating brand using a cte
 
 with top_brand as
 (
 select brand, sum(no_of_tickets * price_per_ticket) total_revenue
 from ticket_details
 group by brand
 )
 select * from top_brand
 order by total_revenue desc limit 1;
 
-- Display customer name,flight number,origin airport,destination airport, and ticket price
-- for all customers who have booked tickets

select * from customer;
select * from passenger;
select * from ticket_details;
select * from routes;  

select c.first_name,c.last_name,p.flight_num,
r.origin_airport,r.destination_airport,t.price_per_ticket
from customer c
join passenger p 
on
c.customer_id = p.customer_id
join routes r 
on p.route_id = r.route_id
join ticket_details t
on 
p.customer_id = t.customer_id
where t.no_of_tickets >=1;

-- find customers who have travelled more than once. display customer name and total flights travelled

select c.first_name,c.last_name,count(distinct flight_num) as total_flights
from customer c 
join passenger p
on
c.customer_id = p.customer_id
group by c.first_name,c.last_name,c.customer_id
having count( distinct flight_num)>2;


select * from customer;
select * from passenger;
select * from ticket_details;
select * from routes;

-- find cutomers whose total ticket spending is greater than the average spending of all customers

select customer_id,sum(no_of_tickets * price_per_ticket) as total_reveue
from ticket_details
group by customer_id
having sum(no_of_tickets * price_per_ticket) >
(
select avg(customer_total)
from
 (
   select sum(no_of_tickets * price_per_ticket) as customer_total
   from ticket_details
   group by customer_id
  ) x
);

-- find the route with the maximum distance miles

select * 
from routes
where distance_miles =
(select max(distance_miles) from routes);


-- find the top 3 customers who booked the highest number of tickets

select customer_id,sum(no_of_tickets) as total_tickets
from ticket_details
group by customer_id
order by sum(no_of_tickets) desc limit 3 ;

-- display revenue generated by each brand and show only brands generatinmg more than 50000 revenue

select brand,sum(no_of_tickets * price_per_ticket) as total_revenue
from ticket_details
group by brand
having sum(no_of_tickets * price_per_ticket) > 5000;

-- Display total tickets booked by each brand along with the grand total

select * from ticket_details;

select brand,sum(no_of_tickets)
from ticket_details
group by brand with rollup;

-- Display revenue by brand and class~id including subtotals and grand total

select
 coalesce(brand, 'Grand total') as brand,
 ifnull(class_id,'Subtotal')as class,
 sum(no_of_tickets * price_per_ticket) as revenue
from ticket_details
group by brand,class_id with rollup;


select * from customer;
select * from passenger;employee
select * from ticket_details;
select * from routes;

-- create a view that displays customer name, flight num,travel date,seat num

create view vw_customer_details
as
select c.first_name,c.last_name, r.flight_num,
p.travel_date,p.seat_num from
customer c
join passenger p
on c.customer_id = p.customer_id
join routes r
on
r.route_id = p.route_id;

select * from vw_customer_details;

-- create a view named customer_booking_summary that displays customer name,brand,total tickets booked,total amount paid

create view vw_customer_ticket_detail
as
select c.first_name,c.last_name, t.brand,
sum(no_of_tickets) as total_tickets,sum(no_of_tickets * price_per_ticket) as total_amount_paid
from customer c 
join ticket_details t
on c.customer_id = t.customer_id
group by c.first_name,c.last_name,t.brand;

select * from vw_customer_ticket_detail;

-- using a cte, calculate the total amount spent by each customer and dispplay .customer name,total amount spent

with customer_spent as
(
select concat(c.first_name,' ',c.last_name) as name,
sum(no_of_tickets * price_per_ticket) as total_price
from customer c
join ticket_details t 
on c.customer_id = t.customer_id
group by concat(c.first_name,' ',c.last_name)
)
select * from customer_spent
where total_price>400;

-- using a cte,calculate the revenue generated by each brand.from the cte,display 
-- only the brands whose revenue is greater than the average revenue of all brand

with brand_revenue
as
(
select brand,sum(no_of_tickets * price_per_ticket) as total_revenue
from ticket_details
group by brand
)
select * from brand_revenue
where total_revenue >
(select avg(total_revenue) from brand_revenue);

-- display customer_name,brand,total amount paid,row number  based on the highest amount spent


select * from ticket_details;

select c.first_name,c.last_name,
t.brand,(t.no_of_tickets * t.price_per_ticket) as total_spent,
row_number()over(order by (t.no_of_tickets * t.price_per_ticket) desc) as highest_spent_wise
from customer c
join ticket_details t
on
c.customer_id = t.customer_id;

-- for each airline brand, rank customers based on the amount they spent

select 
   customer_name,
   brand,
   total_spent,
   rank()over
   (partition by brand order by total_spent desc
   )as rank_wise
from
( 
  
    select c.customer_id,concat(c.first_name,' ',c.last_name) as customer_name,
    t.brand,sum(no_of_tickets*price_per_ticket) as total_spent
    from customer c
    join ticket_details t
    on
    c.customer_id = t.customer_id
    group by c.customer_id,customer_name,t.brand
)as customer_spending;

-- using a cte, find the top 2 customers from each airline brand based on total spending
with customer_spending
as
( 
   select c.customer_id,concat(c.first_name,' ',c.last_name) as customer_name,
    t.brand,sum(no_of_tickets*price_per_ticket) as total_spent
    from customer c
    join ticket_details t
    on
    c.customer_id = t.customer_id
    group by c.customer_id,customer_name,t.brand
),
top2_customers as
(
   select *,
   dense_rank()over(partition by brand order by total_spent desc 
    ) as rank_wise from customer_spending
)
select * from top2_customers where rank_wise <=2;

   




with top2_customers
as
( 
   select c.customer_id,concat(c.first_name,' ',c.last_name) as customer_name,
    t.brand,sum(no_of_tickets*price_per_ticket) as total_spent
    from customer c
    join ticket_details t
    on
    c.customer_id = t.customer_id
    group by c.customer_id,customer_name,t.brand
) 
select *,
dense_rank()over(partition by brand order by total_spent desc) as rank_wise
from top2_customers
where rank_wise <=2;



-- display each customer travel history in chronological order
select * from customer;
select * from passenger;
select * from ticket_details;
select * from routes;

select customer_id,travel_date,
lag(travel_date)over(partition by customer_id order by travel_date) as previous_trip
from passenger;

desc passenger;
select 
   concat(c.first_name,' ',c.last_name) as name,
   p.travel_date,
   p.flight_num,
   lag(p.travel_date)over(
                      partition by c.customer_id order by str_to_date(p.travel_date,'%d-%m-%Y')
                      ) as previous_flight_date,
   datediff(str_to_date(p.travel_date,'%d-%m-%Y'),str_to_date(lag(p.travel_date)over(
                      partition by c.customer_id order by p.travel_date),'%d-%m-%Y')
		  )as days_between_trips
from customer c
join passenger p
on
c.customer_id = p.customer_id;

   
-- Lead
 -- Display each customer travel history in chronical order,customer name,travel date,flight num,next  flight date
 
 select 
   concat(c.first_name,' ',c.last_name) as name,
   p.travel_date,p.flight_num,
   lead(p.travel_date)over(partition by c.customer_id order by p.travel_date) as next_flight_date
   from customer c 
   join passenger p
   on
   c.customer_id = p.customer_id;

 -- Display each customer travel history in chronical order,customer name,travel date,flight num,next  flight date,days untill next trip
 
 with customer_plan
 as
 (
    select 
   concat(c.first_name,' ',c.last_name) as name,
   p.travel_date,p.flight_num,
   lead(p.travel_date)over(partition by c.customer_id order by p.travel_date) as next_flight_date
   from customer c 
   join passenger p
   on
   c.customer_id = p.customer_id
)
select *,datediff(
     str_to_date(next_flight_date,'%d-%m-%Y'),str_to_date(travel_date,'%d-%m-%Y')) as days_untill_next_trip
from customer_plan;

-- first_value
-- display customer name,brand,amount spent,highest spending customer
select 
    brand,
    concat(c.first_name,' ',c.last_name) as name,
    (t.no_of_tickets*t.price_per_ticket) as total_spent,
    first_value(concat(c.first_name,' ',c.last_name))
    over(partition by brand order by (t.no_of_tickets*t.price_per_ticket) desc
    ) as highest_customer
from customer c
join ticket_details t
on c.customer_id = t.customer_id;

-- display each customer travel history customer name,travel date,flight num,first flight number they ever travelled in
select * from customer;
select * from passenger;
select * from ticket_details;
select * from routes;
select
    concat(c.first_name,' ',c.last_name) as name,
    p.travel_date,p.flight_num,
    first_value(p.flight_num)over(partition by concat(c.first_name,' ',c.last_name)) as first_flight_num
from customer c
join passenger p
on c.customer_id = p.customer_id;

/* Business Scenario

The airline wants to identify its top-spending customer in each airline brand.

Question

Using a CTE and a window function, display:

Brand
Customer ID
Customer Name
Total Amount Spent
Rank within the Brand

Return only the top-spending customer for each brand.

Expected Concepts
CTE
JOIN
GROUP BY
SUM()
RANK() or DENSE_RANK()*/

select * from customer;
select * from passenger;
select * from ticket_details;
select * from routes;

with top_spending_customer
as
(
select c.customer_id,concat(c.first_name,'',c.last_name) as full_name,t.brand,
sum(no_of_tickets * price_per_ticket) as total_amount_spent
from customer c
join ticket_details t
on c.customer_id = t.customer_id
group by c.customer_id,concat(c.first_name,'',c.last_name),t.brand
),
ranked_customer as
(
select *,
dense_rank()over(partition by brand order by total_amount_spent desc ) as rank_wise
from top_spending_customer
)
select * from ranked_customer where rank_wise = 1;

/*
Question 2 (Subquery + GROUP BY + HAVING) ⭐⭐⭐⭐
Business Scenario

Management wants to reward loyal customers.

Question

Find customers who:

Have booked more tickets than the average number of tickets booked by all customers.

Display:

Customer ID
Customer Name
Total Tickets
Total Amount Spent

Sort by Total Amount Spent in descending order. */

select c.customer_id,concat(c.first_name,' ',c.last_name) as full_name,
 sum(no_of_tickets) as total_tickets,sum(no_of_tickets * price_per_ticket) as total_amount_spent
from customer c
join ticket_details t
on c.customer_id = t.customer_id
group by c.customer_id,full_name
having total_tickets >
               (select avg(total_ticket)
               from
                (
                  select sum(no_of_tickets)as total_ticket from ticket_details
                  group by customer_id
			    ) as x
               );
			


    
select customer_id ,(no_of_tickets * price_per_ticket) from ticket_details where brand = 'Emirates';
